//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicacion.WebServiceCorresponsal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Corresponsal", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Corresponsal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodCorresponsalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCorresponsalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCorresponsal {
            get {
                return this.CodCorresponsalField;
            }
            set {
                if ((this.CodCorresponsalField.Equals(value) != true)) {
                    this.CodCorresponsalField = value;
                    this.RaisePropertyChanged("CodCorresponsal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCorresponsal {
            get {
                return this.NombreCorresponsalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCorresponsalField, value) != true)) {
                    this.NombreCorresponsalField = value;
                    this.RaisePropertyChanged("NombreCorresponsal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceCorresponsal.IWSTestAsp")]
    public interface IWSTestAsp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTestAsp/getCorresponsal", ReplyAction="http://tempuri.org/IWSTestAsp/getCorresponsalResponse")]
        WebAplicacion.WebServiceCorresponsal.Corresponsal getCorresponsal(int CodCorresponsal, string NombreCorresponsal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTestAsp/getCorresponsal", ReplyAction="http://tempuri.org/IWSTestAsp/getCorresponsalResponse")]
        System.Threading.Tasks.Task<WebAplicacion.WebServiceCorresponsal.Corresponsal> getCorresponsalAsync(int CodCorresponsal, string NombreCorresponsal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTestAspChannel : WebAplicacion.WebServiceCorresponsal.IWSTestAsp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTestAspClient : System.ServiceModel.ClientBase<WebAplicacion.WebServiceCorresponsal.IWSTestAsp>, WebAplicacion.WebServiceCorresponsal.IWSTestAsp {
        
        public WSTestAspClient() {
        }
        
        public WSTestAspClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTestAspClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTestAspClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTestAspClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAplicacion.WebServiceCorresponsal.Corresponsal getCorresponsal(int CodCorresponsal, string NombreCorresponsal) {
            return base.Channel.getCorresponsal(CodCorresponsal, NombreCorresponsal);
        }
        
        public System.Threading.Tasks.Task<WebAplicacion.WebServiceCorresponsal.Corresponsal> getCorresponsalAsync(int CodCorresponsal, string NombreCorresponsal) {
            return base.Channel.getCorresponsalAsync(CodCorresponsal, NombreCorresponsal);
        }
    }
}
